sudo: true
dist: trusty
osx_image: xcode8.3
language: c

script:
- make test
os:
- linux
- osx
env:
  global:
  - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
addons:
  apt:
    packages:
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - libssl-dev
    - libpcsclite-dev
  coverity_scan:
    project:
      name: open-eid/chrome-token-signing
    notification_email: martin@martinpaljak.net
    build_command: make
    branch_pattern: coverity_scan
