sudo: true
dist: trusty
language: c

script:
- make test
os:
- linux
- osx
env:
  global:
  - secure: oRtk0cC35ItGNDY0z9gRenVW8qTE8St+XmhFNkh/K4BWLp5vMzv+hOBzXK9ZJ38prppcGur6evVNqJ7NCrGyH6DjS3TjBzd/FalvD1lEZyAKPKVihHjLwOr2uayt6nGhA7wt7HlFLvL1pfiuWnR6tFWxP3fI8duuu0x9N0ILyu0=
addons:
  apt:
    packages:
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - libssl-dev
    - libpcsclite-dev
  coverity_scan:
    project:
      name: open-eid/chrome-token-signing
    notification_email: martin@martinpaljak.net
    build_command_prepend: 
    build_command: make
    branch_pattern: coverity_scan
